### ISSUE TITLE
results

### ISSUE THREAD

**Issue by fengjingchehu** [lihaoliu-cambridge/scotch-and-soda#1]
hello,i got nothing in my output\results\scotch_and_soda_visha_image\pred\dataset.
In this regard, I am a beginner, and I would like to know if I have made any mistakes. 
Looking forward to your response.

**Comment by lihaoliu-cambridge** [comment]
> hello,i got nothing in my output\results\scotch_and_soda_visha_image\pred\dataset. In this regard, I am a beginner, and I would like to know if I have made any mistakes. Looking forward to your response.

Hi, I don't think this is the correct path for generated results. It should be output\results\scotch_and_soda_visha_image\pred, without the \dataset folder.
